<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>spot_flex_plan</name>
  <version>0.1.0</version>
  <description>Task planning and orchestration for spot_flex</description>
  <maintainer email="timothy.duggan@tufts.edu">Timothy Duggan</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>geometry_msgs</depend>
  <depend>spot_flex_msgs</depend>
  <depend>spot_msgs</depend>
  <depend>nav2_msgs</depend>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>spot_flex_nav</exec_depend>
  <exec_depend>spot_flex_moveit</exec_depend>
  <exec_depend>yasmin</exec_depend>
  <exec_depend>yasmin_ros</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
